development:
  adapter: postgresql
  encoding: unicode
  database: development_dleung_2
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

production:
  adapter: postgresql
  encoding: unicode
  database: production_dleung_2
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

test:
  adapter: postgresql
  encoding: unicode
  database: test_dleung_2
  pool: 5
  username: quosap
  password: graceling
  host: /tmp
