development:
  adapter: postgresql
  encoding: unicode
  database: capykoa_development
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

production:
  adapter: postgresql
  encoding: unicode
  database: capykoa_production
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

test:
  adapter: postgresql
  encoding: unicode
  database: capykoa_test
  pool: 5
  username: quosap
  password: graceling
  host: /tmp
