development:
  adapter: mysql2
  encoding: utf8
  database: development_dleung_3
  username: root
  password: capykoa1016

production:
  adapter: mysql2
  encoding: utf8
  database: production_dleung_3
  username: root
  password: capykoa1016

test:
  adapter: mysql2
  encoding: utf8
  database: test_dleung_3
  username: root
  password: capykoa1016
